{{- if and (ne .Values.clusterProfile "Serverless") .Values.enableHybrid }}
---
# loongcollector-ds-hybrid

apiVersion: v1
kind: ServiceAccount
metadata:
  name: loongcollector-ds-hybrid
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: loongcollector-ds-hybrid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loongcollector-ds-hybrid
  labels:
    app: loongcollector-ds-hybrid
rules:
- apiGroups:
  - "*"
  resources:
  - "nodes"
  - "nodes/metrics"
  verbs:
  - get
- apiGroups: [""] # "" indicates the core API group
  resources:
  - configmaps
  verbs:
  - update
  - get
  resourceNames:         # 限制名称
  - "alibaba-log-configuration"
- apiGroups:
    - ""
  resources:
    - "configmaps"
  verbs:
    - "create"  
- apiGroups: [""] # "" indicates the core API group
  resources:
  - events
  verbs:
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loongcollector-ds-hybrid-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: loongcollector-ds-hybrid
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: loongcollector-ds-hybrid
  apiGroup: rbac.authorization.k8s.io

{{- end }}
