serviceName: reward-mservice

image:
  repository: crpi-m8e4ka9sicipqhhl.ap-southeast-1.personal.cr.aliyuncs.com/campaign-center/reward-mservice
  tag: dev-202607111241
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

replicaCount: 1

containerPorts:
  http: 8080
  grpc: 5001

probes:
  liveness:
    path: /reward-ms/v1/ping
  readiness:
    path: /reward-ms/v1/ping

configFile:
  enabled: true
  name: config.yml
  mountPath: /app/resources/config.yml
  content:
    grpc:
      host: "0.0.0.0"
      port: 5001
      connect_timeout: 3
      max_pool_size: 200
    http:
      host: "0.0.0.0"
      port: 8080
    log:
      level: debug
      file_path: ./logs/reward-mservice.log
    system:
      service_name: reward-mservice
      allowed_origins:
        - https://campaign-center-admin-web.vercel.app
        - https://finverse-web.vercel.app
        - http://localhost:3000
    kafka:
      enabled: true
      brokers:
        - kafka.messaging.svc.cluster.local:9092
      group_id: reward-mservice
      client_id: reward-mservice
      topics:
        - reward.finance_doc.approved
        - reward.issue_request.approved
        - reward.distribution.execute
        - reward.distribution.result

externalSecret:
  enabled: true
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  targetSecretName: reward-mservice-secret
  refreshInterval: 1h
  remoteRef:
    key: campaign-center/dev/reward-mservice

envFromSecret:
  enabled: true
  secretName: reward-mservice-secret

service:
  type: ClusterIP
  ports:
    http: 8080
    grpc: 5001

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
