serviceName: campaign-center-api

image:
  repository: crpi-m8e4ka9sicipqhhl.ap-southeast-1.personal.cr.aliyuncs.com/campaign-center/campaign-center-api
  tag: dev-202608011205
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

replicaCount: 1

containerPorts:
  http: 8080
  grpc: 5000

probes:
  liveness:
    path: /campaign-center-api/v1/ping
  readiness:
    path: /campaign-center-api/v1/ping

configFile:
  enabled: true
  name: config.yml
  mountPath: /app/resources/config.yml
  content:
    http:
      host: "0.0.0.0"
      port: 8080
    log:
      level: info
      file_path: ./logs/campaign-center-api.log
    grpc:
      host: "0.0.0.0"
      port: 5000
      connect_timeout: 5
      max_pool_size: 100
    redis:
      enabled: false
      host: redis.redis.svc.cluster.local
      port: "6379"
    openai:
      api_key: ""
      base_url: ""
      model: "gpt-4o-mini"
    system:
      allowed_origins:
        - https://campaign-center-admin-web.vercel.app
        - https://finverse-web.vercel.app
        - http://localhost:3000

externalSecret:
  enabled: true
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  targetSecretName: campaign-center-api-secret
  refreshInterval: 1h
  remoteRef:
    key: campaign-center/dev/campaign-center-api

envFromSecret:
  enabled: true
  secretName: campaign-center-api-secret

service:
  type: ClusterIP
  ports:
    http: 8080
    grpc: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
