apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo1-loongcollector-pipeline
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/nusiss-capstone-project/campaign-gitops.git
    targetRevision: demo1
    path: platform/loongcollector/pipelines
    directory:
      include: "campaign-demo1-stdout.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: telemetry.alibabacloud.com
      kind: ClusterAliyunPipelineConfig
      jsonPointers:
        - /status
        - /metadata/generation
        - /metadata/annotations
        - /metadata/managedFields
        - /metadata/finalizers
