apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mockpass
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nusiss-capstone-project/campaign-gitops.git
    targetRevision: dev
    path: apps/mockpass
  destination:
    server: https://kubernetes.default.svc
    namespace: mockpass
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
