apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reward-mservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nusiss-capstone-project/campaign-gitops.git
    targetRevision: dev
    path: charts/go-service
    helm:
      valueFiles:
        - ../../apps/reward-mservice/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: campaign-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
